from typing import Protocol
from uuid import UUID

from src.modules.storage.models import File


class ObjectStoreProtocol(Protocol):
    def put_object(self, path: str, data: bytes, content_type: str) -> dict: ...
    def get_object(self, path: str) -> tuple[bytes, str]: ...
    def delete_object(self, path: str) -> bool: ...
    def get_signed_url(self, path: str, expires_in: int = 3600) -> str | None: ...
    def object_exists(self, path: str) -> bool: ...


class FileRepositoryProtocol(Protocol):
    async def create(self, **kwargs) -> File: ...
    async def get_by_id(self, file_id: UUID) -> File | None: ...
    async def list_by_project(
        self,
        project_id: UUID,
        file_type: str | None = None,
        include_deleted: bool = False,
    ) -> list[File]: ...
    async def soft_delete(self, file_id: UUID) -> None: ...
