from typing import Protocol
from uuid import UUID

from src.modules.auth.models import Organization, OrganizationMember, User


class UserRepositoryProtocol(Protocol):
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def get_by_user_id(self, user_id: str) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def create(self, user_id: str, name: str, email: str) -> User: ...
    async def update_last_login(self, user_id: UUID) -> None: ...
    async def set_verification_token(self, user_id: UUID, token: str) -> None: ...
    async def verify_user(self, user_id: UUID) -> None: ...
    async def get_by_verification_token(self, token: str) -> User | None: ...


class OrganizationRepositoryProtocol(Protocol):
    async def get_by_name(self, name: str) -> Organization | None: ...
    async def create(self, name: str) -> Organization: ...
    async def create_member(self, user_id: UUID, org_id: UUID, role: str) -> OrganizationMember: ...
