from datetime import datetime
from typing import Protocol
from uuid import UUID

from src.modules.auth.models import Organization, OrganizationMember, RefreshToken, User


class UserRepositoryProtocol(Protocol):
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def get_by_user_id(self, user_id: str) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def create(self, user_id: str, name: str, email: str) -> User: ...
    async def update_last_login(self, user_id: UUID) -> None: ...
    async def set_verification_token(self, user_id: UUID, token: str) -> None: ...
    async def verify_user(self, user_id: UUID) -> None: ...
    async def get_by_verification_token(self, token: str) -> User | None: ...
    async def set_magic_link_token(self, user_id: UUID, token: str) -> None: ...
    async def get_by_magic_link_token(self, token: str) -> User | None: ...
    async def clear_magic_link_token(self, user_id: UUID) -> None: ...


class RefreshTokenRepositoryProtocol(Protocol):
    async def create(self, user_id: UUID, token_hash: str, expires_at: datetime) -> RefreshToken: ...
    async def get_by_token_hash(self, token_hash: str) -> RefreshToken | None: ...
    async def revoke(self, token_hash: str) -> None: ...
    async def revoke_all_for_user(self, user_id: UUID) -> None: ...


class OrganizationRepositoryProtocol(Protocol):
    async def get_by_name(self, name: str) -> Organization | None: ...
    async def create(self, name: str) -> Organization: ...
    async def create_member(self, user_id: UUID, org_id: UUID, role: str) -> OrganizationMember: ...
    async def get_memberships_for_user(self, user_id: UUID) -> list: ...
