from typing import Protocol
from uuid import UUID

from coa_db_models.mappings.models import AccountTypeMapping


class AccountTypeMappingRepositoryProtocol(Protocol):
    async def bulk_replace(
        self, project_id: UUID, mappings: list[dict], mapping_file_id: UUID | None, created_by: UUID
    ) -> int: ...
    async def list_by_project(self, project_id: UUID) -> list[AccountTypeMapping]: ...
    async def get_by_id(self, id: UUID) -> AccountTypeMapping | None: ...
    async def update(self, obj: AccountTypeMapping, data: dict) -> AccountTypeMapping: ...
    async def delete_by_project(self, project_id: UUID) -> int: ...
