from typing import Any, Protocol
from uuid import UUID

from coa_db_models.auth.models import OrganizationMember
from coa_db_models.projects.models import Project, ProjectAccess


class ProjectRepositoryProtocol(Protocol):
    async def get_by_id(self, id: UUID) -> Project | None: ...
    async def get_by_id_with_users(self, project_id: UUID) -> Any | None: ...
    async def list_by_ids(self, project_ids: list[UUID]) -> list[Project]: ...
    async def list_by_ids_with_users(self, project_ids: list[UUID]) -> list[Any]: ...
    async def list_by_org(self, org_id: UUID, skip: int = 0, limit: int = 50) -> list[Project]: ...
    async def create_project(self, **kwargs) -> Project: ...
    async def update(self, obj: Project, data: dict) -> Project: ...
    async def update_status(self, project_id: UUID, status: str) -> None: ...
    async def delete(self, id: UUID) -> None: ...
    async def get_overview_workstreams(self, project_id: UUID) -> list[Any]: ...
    async def get_stage_counts(self, workstream_ids: list[UUID]) -> dict[UUID, int]: ...


class ProjectAccessRepositoryProtocol(Protocol):
    async def get_user_permission(self, user_id: UUID, project_id: UUID) -> ProjectAccess | None: ...
    async def list_for_project(self, project_id: UUID) -> list[dict]: ...
    async def list_for_user(self, user_id: UUID) -> list[ProjectAccess]: ...
    async def grant(self, user_id: UUID, project_id: UUID, permission: str, assigned_by: UUID) -> ProjectAccess: ...
    async def revoke(self, user_id: UUID, project_id: UUID) -> None: ...


class OrgMembershipReaderProtocol(Protocol):
    """Slice of OrganizationRepository used for project access checks."""

    async def get_member(self, org_id: UUID, user_id: UUID) -> OrganizationMember | None: ...
