from typing import Protocol
from uuid import UUID

from src.modules.projects.models import Company, Project, ProjectAccess


class CompanyRepositoryProtocol(Protocol):
    async def get_by_id(self, company_id: UUID) -> Company | None: ...
    async def get_by_slug(self, slug: str) -> Company | None: ...
    async def create(self, slug: str, name: str, description: str | None = None) -> Company: ...
    async def get_or_create(self, slug: str, name: str | None = None) -> Company: ...
    async def list_by_ids(self, company_ids: list[UUID]) -> list[Company]: ...


class ProjectRepositoryProtocol(Protocol):
    async def get_by_id(self, project_id: UUID) -> Project | None: ...
    async def list_by_ids(self, project_ids: list[UUID]) -> list[Project]: ...
    async def list_by_company(self, company_id: UUID, skip: int = 0, limit: int = 50) -> list[Project]: ...
    async def create(self, **kwargs) -> Project: ...
    async def update(self, project: Project, data: dict) -> Project: ...
    async def update_status(self, project_id: UUID, status: str) -> None: ...
    async def delete(self, project_id: UUID) -> None: ...


class ProjectAccessRepositoryProtocol(Protocol):
    async def get_user_permission(self, user_id: UUID, project_id: UUID) -> ProjectAccess | None: ...
    async def list_for_project(self, project_id: UUID) -> list[dict]: ...
    async def list_for_user(self, user_id: UUID) -> list[ProjectAccess]: ...
    async def grant(self, user_id: UUID, project_id: UUID, permission: str, assigned_by: UUID) -> ProjectAccess: ...
    async def revoke(self, user_id: UUID, project_id: UUID) -> None: ...
